defaults: &defaults
    macos:
      xcode: "11.6.0"
    shell: /bin/bash --login -eo pipefail
aliases:
  - &cache-pull
    keys:
      - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - gem-cache-v1-{{ arch }}-{{ .Branch }}
      - gem-cache-v1
  - &cache-push
    key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
    paths:
      - vendor/bundle
  - &prepare
    |
      git submodule update --init --recursive
      sudo gem install bundler
      bundle config set path 'vendor/bundle'
      bundle install
  - &filter-only-master
    branches:
      only:
        - master

version: 2
jobs:
  ios:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *cache-pull
      - run: *prepare
      - save_cache: *cache-push
      - run: bundle exec rake test:ios
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: build/reports
  macos:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *cache-pull
      - run: *prepare
      - save_cache: *cache-push
      - run:
          name: "Create and set the default keychain"
          command: |
            security create-keychain -p "" temporary
            security default-keychain -s temporary
            security unlock-keychain -p "" temporary
            security set-keychain-settings -lut 7200 temporary
      - run: bundle exec rake test:macos
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: build/reports
      - store_artifacts:
          path: build/reports
          destination: test_results
  carthage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *cache-pull
      - run: *prepare
      - save_cache: *cache-push
      - run: bundle exec rake test:carthage

workflows:
  version: 2
  pr:
    jobs:
      - ios
      - macos
      - carthage
  nightly:
    jobs:
      - carthage
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters: *filter-only-master
