language: objective-c
os: osx

env:
  global:
    # $api_key
    - secure: vjVOdxnuHnkDiPXoddLycTQ2WwbYudHU53xbaz86Su0J+xTSNDmxmd2GFn45EMn5BixwVzTnLWhDg7EvNvQhHWDAuHUaK7X/KXoR41s3PzlucWtxczxxt3eIRtk7U4y22tSwr/r1cl6Q2QM5IK8ICZshhSyiHHEz/EAaodcJkUE=
    # $COCOAPODS_TRUNK_TOKEN
    - secure: mpObzf4FG+JHEN6Gm/Jp96pLONe4nYpgtXxkRLlULlD23c6aHAwMJhT/pjYKINmBmxd0/Vnw5LVvBcU0rCrjANFn4nfotP4KoexIO4As+wjRGAmd9IUvosio9zdv1DasUZlHliyPElfsbKqK3aZjBDw1Cx99t6dog0H6aIKUOQA=
    - XCODE_WORKSPACE=FacebookSDK.xcworkspace
    - GITHUB_ACCESS_TOKEN=$api_key

branches:
  only:
    - master
    - 4.x-branch
    - /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/

stages:
  - name: test
    if: '! tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/'
  # - name: tag
  #   if: '! tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/'
  - name: release
    if: tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/

jobs:
  include:
    - stage: test
      name: Xcode - iOS 12.2
      osx_image: xcode10.2
      env:
        - XCODE_SDK=iphonesimulator12.2
        - XCODE_SCHEME=BuildAllKits
    - stage: test
      name: Xcode - tvOS 12.2
      osx_image: xcode10.2
      env:
        - XCODE_SDK=appletvsimulator12.2
        - XCODE_SCHEME=BuildAllKits_TV
    - stage: test
      name: Xcode - iOS 11.4
      osx_image: xcode9.4
      env:
        - XCODE_SDK=iphonesimulator11.4
        - XCODE_SCHEME=BuildAllKits
    - stage: test
      name: Carthage - Xcode 10.2
      osx_image: xcode10.2
    - stage: test
      name: Pod Lint - Xcode 10.2
      osx_image: xcode10.2
      script: sh scripts/run.sh lint cocoapods --allow-warnings
    # - stage: tag
    #   name: Tag Version
    #   osx_image: xcode10.2
    #   script: sh scripts/run.sh tag-current-version --push
    - stage: release
      name: GitHub Release
      osx_image: xcode10.2
      script: sh scripts/run.sh build carthage --archive
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_ACCESS_TOKEN
        file: Carthage/Release/*
        file_glob: true
        name: Facebook SDK $TRAVIS_TAG
        body: Consult Changelog $TRAVIS_TAG
        on:
          all_branches: true
          tags: true
    - stage: release
      name: Publish Cocoapods
      osx_image: xcode10.2
      script: sh scripts/run.sh release cocoapods --allow-warnings

before_install: sh scripts/travis/before_install.sh
install: sh scripts/travis/install.sh
script: sh scripts/travis/script.sh

notifications: # set notification options
  email:
    on_success: change
    on_failure: always
    recipients:
      - codytwinton@fb.com
  # Enable webhooks later
  # webhooks:
  # on_failure: always
