//
//  PodliveGUIKit.h
//  Podlive
//
//  Created by Frank Gregor on 14/06/2017.
//  Copyright © 2017 cocoa:naut. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <Cocoa/Cocoa.h>



typedef enum : NSInteger
{
    PodliveGUIKitResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    PodliveGUIKitResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    PodliveGUIKitResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    PodliveGUIKitResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} PodliveGUIKitResizingBehavior;

extern NSRect PodliveGUIKitResizingBehaviorApply(PodliveGUIKitResizingBehavior behavior, NSRect rect, NSRect target);


@interface PodliveGUIKit : NSObject

// Drawing Methods
+ (void)drawProgressBarWithFrame: (NSRect)frame color: (NSColor*)color progressBarActiveColor: (NSColor*)progressBarActiveColor progress: (CGFloat)progress;
+ (void)drawPlayButtonWithColor: (NSColor*)color radius: (CGFloat)radius borderWidth: (CGFloat)borderWidth;
+ (void)drawPlayButtonWithFrame: (NSRect)targetFrame resizing: (PodliveGUIKitResizingBehavior)resizing color: (NSColor*)color radius: (CGFloat)radius borderWidth: (CGFloat)borderWidth;
+ (void)drawStopButtonWithColor: (NSColor*)color radius: (CGFloat)radius borderWidth: (CGFloat)borderWidth;
+ (void)drawStopButtonWithFrame: (NSRect)targetFrame resizing: (PodliveGUIKitResizingBehavior)resizing color: (NSColor*)color radius: (CGFloat)radius borderWidth: (CGFloat)borderWidth;
+ (void)drawPauseButtonWithColor: (NSColor*)color radius: (CGFloat)radius borderWidth: (CGFloat)borderWidth;
+ (void)drawPauseButtonWithFrame: (NSRect)targetFrame resizing: (PodliveGUIKitResizingBehavior)resizing color: (NSColor*)color radius: (CGFloat)radius borderWidth: (CGFloat)borderWidth;
+ (void)drawPlayerListenerWithFrame: (NSRect)frame color: (NSColor*)color;
+ (void)drawPlayerTimerClockWithFrame: (NSRect)frame color: (NSColor*)color;
+ (void)drawAnonymousAvatarWithFrame: (NSRect)frame color: (NSColor*)color;

// Generated Images
+ (NSImage*)imageOfPlayButtonWithColor: (NSColor*)color radius: (CGFloat)radius borderWidth: (CGFloat)borderWidth;
+ (NSImage*)imageOfStopButtonWithColor: (NSColor*)color radius: (CGFloat)radius borderWidth: (CGFloat)borderWidth;
+ (NSImage*)imageOfPauseButtonWithColor: (NSColor*)color radius: (CGFloat)radius borderWidth: (CGFloat)borderWidth;
+ (NSImage*)imageOfPlayerListenerWithSize: (NSSize)imageSize color: (NSColor*)color;
+ (NSImage*)imageOfPlayerTimerClockWithSize: (NSSize)imageSize color: (NSColor*)color;
+ (NSImage*)imageOfAnonymousAvatarWithSize: (NSSize)imageSize color: (NSColor*)color;

@end
