//
//  PodliveDefaultStyleKit.h
//  Podlive
//
//  Created by Frank Gregor on 01/07/2017.
//  Copyright © 2017 cocoa:naut. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <Cocoa/Cocoa.h>


@interface PodliveDefaultStyleKit : NSObject

// Colors
+ (NSColor*)podliveBaseColor;
+ (NSColor*)trialRemainingColor;
+ (NSColor*)userLoggedInStatusColor;
+ (NSColor*)userLoggedOutStatusColor;
+ (NSColor*)gridItemSubscriptionBadgeColor;
+ (NSColor*)controlTextColor;
+ (NSColor*)controlLightenColor;
+ (NSColor*)controlDarkenColor;
+ (NSColor*)controlButtonNormalColor;
+ (NSColor*)controlButtonHighlightColor;
+ (NSColor*)controlButtonBackgroundColor;
+ (NSColor*)gridItemDetailDarkColor;
+ (NSColor*)gridSectionHeaderColor;
+ (NSColor*)controlTextDarkColor;
+ (NSColor*)gridSectionHeaderTextColor;
+ (NSColor*)gridItemDetailColor;
+ (NSColor*)gridItemDetailTextColor;
+ (NSColor*)gridItemDetailTopLineColor;
+ (NSColor*)gridItemDetailBottomLineColor;
+ (NSColor*)playerBackgroundColor;
+ (NSColor*)playerTextColor;
+ (NSColor*)playerLightenColor;
+ (NSColor*)playerDarkenColor;
+ (NSColor*)playerButtonHighlightColor;
+ (NSColor*)playerButtonBorderDarkColor;
+ (NSColor*)playerButtonBackgroundColor;
+ (NSColor*)playerButtonBorderColor;
+ (NSColor*)gridItemSubscriptionBadgeDarkColor;
+ (NSColor*)gridSectionHeaderTextDarkColor;
+ (NSColor*)playerTextDarkColor;
+ (NSColor*)gridSectionHeaderDarkColor;
+ (NSColor*)gridItemDetailTextDarkColor;
+ (NSColor*)playerBackgroundDarkColor;
+ (NSColor*)playerLightenDarkColor;
+ (NSColor*)playerDarkenDarkColor;
+ (NSColor*)playerButtonBackgroundDarkColor;
+ (NSColor*)playerButtonHighlightDarkColor;
+ (NSColor*)userLoggedOutStatusDarkColor;
+ (NSColor*)gridItemDetailBottomLineDarkColor;
+ (NSColor*)gridItemDetailTopLineDarkColor;
+ (NSColor*)gridItemSelectionForegroundColor;
+ (NSColor*)gridItemSelectionBackgroundColor;
+ (NSColor*)gridItemSelectionBackgroundDarkColor;
+ (NSColor*)gridItemDetailMarkerColor;
+ (NSColor*)gridItemDetailMarkerDarkColor;
+ (NSColor*)gridItemSelectionForegroundDarkColor;
+ (NSColor*)userLoggedInStatusDarkColor;

@end
