//
//  PodliveDefaultStyleKit.m
//  Podlive
//
//  Created by Frank Gregor on 01/07/2017.
//  Copyright © 2017 cocoa:naut. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import "PodliveDefaultStyleKit.h"


@implementation PodliveDefaultStyleKit

#pragma mark Cache

static NSColor* _podliveBaseColor = nil;
static NSColor* _trialRemainingColor = nil;
static NSColor* _userLoggedInStatusColor = nil;
static NSColor* _userLoggedOutStatusColor = nil;
static NSColor* _gridItemSubscriptionBadgeColor = nil;
static NSColor* _controlTextColor = nil;
static NSColor* _controlLightenColor = nil;
static NSColor* _controlDarkenColor = nil;
static NSColor* _controlButtonNormalColor = nil;
static NSColor* _controlButtonHighlightColor = nil;
static NSColor* _controlButtonBackgroundColor = nil;
static NSColor* _gridItemDetailDarkColor = nil;
static NSColor* _gridSectionHeaderColor = nil;
static NSColor* _controlTextDarkColor = nil;
static NSColor* _gridSectionHeaderTextColor = nil;
static NSColor* _gridItemDetailColor = nil;
static NSColor* _gridItemDetailTextColor = nil;
static NSColor* _gridItemDetailTopLineColor = nil;
static NSColor* _gridItemDetailBottomLineColor = nil;
static NSColor* _playerBackgroundColor = nil;
static NSColor* _playerTextColor = nil;
static NSColor* _playerLightenColor = nil;
static NSColor* _playerDarkenColor = nil;
static NSColor* _playerButtonHighlightColor = nil;
static NSColor* _playerButtonBorderDarkColor = nil;
static NSColor* _playerButtonBackgroundColor = nil;
static NSColor* _playerButtonBorderColor = nil;
static NSColor* _gridItemSubscriptionBadgeDarkColor = nil;
static NSColor* _gridSectionHeaderTextDarkColor = nil;
static NSColor* _playerTextDarkColor = nil;
static NSColor* _gridSectionHeaderDarkColor = nil;
static NSColor* _gridItemDetailTextDarkColor = nil;
static NSColor* _playerBackgroundDarkColor = nil;
static NSColor* _playerLightenDarkColor = nil;
static NSColor* _playerDarkenDarkColor = nil;
static NSColor* _playerButtonBackgroundDarkColor = nil;
static NSColor* _playerButtonHighlightDarkColor = nil;
static NSColor* _userLoggedOutStatusDarkColor = nil;
static NSColor* _gridItemDetailBottomLineDarkColor = nil;
static NSColor* _gridItemDetailTopLineDarkColor = nil;
static NSColor* _gridItemSelectionForegroundColor = nil;
static NSColor* _gridItemSelectionBackgroundColor = nil;
static NSColor* _gridItemSelectionBackgroundDarkColor = nil;
static NSColor* _gridItemDetailMarkerColor = nil;
static NSColor* _gridItemDetailMarkerDarkColor = nil;
static NSColor* _gridItemSelectionForegroundDarkColor = nil;
static NSColor* _userLoggedInStatusDarkColor = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _podliveBaseColor = [NSColor colorWithRed: 0.341 green: 0.192 blue: 0.371 alpha: 1];
    _trialRemainingColor = [NSColor colorWithRed: 0.266 green: 0.784 blue: 0.158 alpha: 1];
    _userLoggedInStatusColor = [NSColor colorWithRed: 0.435 green: 0.831 blue: 0.004 alpha: 1];
    _userLoggedInStatusDarkColor = [_userLoggedInStatusColor shadowWithLevel: 0.3];
    _userLoggedOutStatusColor = [NSColor colorWithRed: 0.718 green: 0.718 blue: 0.718 alpha: 1];
    _userLoggedOutStatusDarkColor = [_userLoggedOutStatusColor shadowWithLevel: 0.5];
    _gridItemSubscriptionBadgeColor = [NSColor colorWithRed: 0.541 green: 0.231 blue: 0.608 alpha: 1];
    _gridItemSubscriptionBadgeDarkColor = [_gridItemSubscriptionBadgeColor highlightWithLevel: 0.2];
    _controlTextColor = [NSColor colorWithRed: 0.189 green: 0.189 blue: 0.189 alpha: 1];
    _controlTextDarkColor = [_controlTextColor highlightWithLevel: 0.8];
    _playerTextColor = [NSColor colorWithHue: _controlTextColor.hueComponent saturation: _controlTextColor.saturationComponent brightness: 0.4 alpha: _controlTextColor.alphaComponent];
    _playerTextDarkColor = [_playerTextColor highlightWithLevel: 0.5];
    _controlLightenColor = [NSColor colorWithRed: 0.984 green: 0.984 blue: 0.984 alpha: 1];
    _controlButtonHighlightColor = [NSColor colorWithHue: _controlLightenColor.hueComponent saturation: _controlLightenColor.saturationComponent brightness: 1 alpha: _controlLightenColor.alphaComponent];
    _playerLightenColor = [NSColor colorWithHue: _controlLightenColor.hueComponent saturation: _controlLightenColor.saturationComponent brightness: 1 alpha: _controlLightenColor.alphaComponent];
    _playerLightenDarkColor = [_playerLightenColor shadowWithLevel: 0.2];
    _controlDarkenColor = [NSColor colorWithRed: 0.867 green: 0.867 blue: 0.867 alpha: 1];
    _playerDarkenColor = [NSColor colorWithHue: _controlDarkenColor.hueComponent saturation: _controlDarkenColor.saturationComponent brightness: 0.867 alpha: _controlDarkenColor.alphaComponent];
    _playerDarkenDarkColor = [_playerDarkenColor shadowWithLevel: 0.2];
    _controlButtonNormalColor = [NSColor colorWithRed: 0.898 green: 0.898 blue: 0.898 alpha: 1];
    _controlButtonBackgroundColor = [NSColor colorWithRed: 0 green: 0 blue: 0 alpha: 0.25];
    _gridSectionHeaderColor = [NSColor colorWithRed: 0.886 green: 0.886 blue: 0.886 alpha: 0];
    _gridSectionHeaderDarkColor = [_gridSectionHeaderColor colorWithAlphaComponent: 0];
    _gridSectionHeaderTextColor = [NSColor colorWithRed: 0.542 green: 0.542 blue: 0.542 alpha: 1];
    _gridSectionHeaderTextDarkColor = [_gridSectionHeaderTextColor highlightWithLevel: 0.6];
    _gridItemDetailColor = [NSColor colorWithRed: 0.847 green: 0.847 blue: 0.847 alpha: 1];
    _gridItemDetailDarkColor = [_gridItemDetailColor shadowWithLevel: 0.86];
    _gridItemDetailTextColor = [NSColor colorWithHue: _gridItemDetailColor.hueComponent saturation: _gridItemDetailColor.saturationComponent brightness: 0.1 alpha: _gridItemDetailColor.alphaComponent];
    _gridItemDetailTextDarkColor = [_gridItemDetailTextColor highlightWithLevel: 0.6];
    _gridItemDetailTopLineColor = [NSColor colorWithRed: 0.62 green: 0.62 blue: 0.62 alpha: 1];
    _gridItemDetailTopLineDarkColor = [_gridItemDetailTopLineColor shadowWithLevel: 1];
    _gridItemDetailBottomLineColor = [NSColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    _gridItemDetailBottomLineDarkColor = [_gridItemDetailBottomLineColor shadowWithLevel: 0.8];
    _playerBackgroundColor = [NSColor colorWithRed: 0.59 green: 0.59 blue: 0.59 alpha: 0.45];
    _playerBackgroundDarkColor = [_playerBackgroundColor colorWithAlphaComponent: 0.9];
    _playerButtonBackgroundColor = [NSColor colorWithRed: 0.114 green: 0.114 blue: 0.114 alpha: 0.405];
    _playerButtonBackgroundDarkColor = _playerButtonBackgroundColor;
    _playerButtonBorderColor = [NSColor colorWithRed: 0.609 green: 0.609 blue: 0.609 alpha: 1];
    _playerButtonHighlightColor = [NSColor colorWithHue: _playerButtonBorderColor.hueComponent saturation: _playerButtonBorderColor.saturationComponent brightness: 0.2 alpha: _playerButtonBorderColor.alphaComponent];
    _playerButtonBorderDarkColor = [NSColor colorWithHue: _playerButtonBorderColor.hueComponent saturation: _playerButtonBorderColor.saturationComponent brightness: 0.65 alpha: _playerButtonBorderColor.alphaComponent];
    _playerButtonHighlightDarkColor = [_playerButtonBorderDarkColor highlightWithLevel: 0.9];
    _gridItemSelectionForegroundColor = [NSColor colorWithRed: 0 green: 0 blue: 0 alpha: 1];
    _gridItemSelectionForegroundDarkColor = [NSColor colorWithHue: _gridItemSelectionForegroundColor.hueComponent saturation: _gridItemSelectionForegroundColor.saturationComponent brightness: 1 alpha: _gridItemSelectionForegroundColor.alphaComponent];
    _gridItemSelectionBackgroundColor = [NSColor colorWithRed: 0.847 green: 0.847 blue: 0.847 alpha: 1];
    _gridItemSelectionBackgroundDarkColor = [_gridItemSelectionBackgroundColor shadowWithLevel: 0.86];
    _gridItemDetailMarkerColor = [NSColor colorWithRed: 0.65 green: 0.395 blue: 0.705 alpha: 1];
    _gridItemDetailMarkerDarkColor = [_gridItemDetailMarkerColor highlightWithLevel: 0.2];

}

#pragma mark Colors

+ (NSColor*)podliveBaseColor { return _podliveBaseColor; }
+ (NSColor*)trialRemainingColor { return _trialRemainingColor; }
+ (NSColor*)userLoggedInStatusColor { return _userLoggedInStatusColor; }
+ (NSColor*)userLoggedOutStatusColor { return _userLoggedOutStatusColor; }
+ (NSColor*)gridItemSubscriptionBadgeColor { return _gridItemSubscriptionBadgeColor; }
+ (NSColor*)controlTextColor { return _controlTextColor; }
+ (NSColor*)controlLightenColor { return _controlLightenColor; }
+ (NSColor*)controlDarkenColor { return _controlDarkenColor; }
+ (NSColor*)controlButtonNormalColor { return _controlButtonNormalColor; }
+ (NSColor*)controlButtonHighlightColor { return _controlButtonHighlightColor; }
+ (NSColor*)controlButtonBackgroundColor { return _controlButtonBackgroundColor; }
+ (NSColor*)gridItemDetailDarkColor { return _gridItemDetailDarkColor; }
+ (NSColor*)gridSectionHeaderColor { return _gridSectionHeaderColor; }
+ (NSColor*)controlTextDarkColor { return _controlTextDarkColor; }
+ (NSColor*)gridSectionHeaderTextColor { return _gridSectionHeaderTextColor; }
+ (NSColor*)gridItemDetailColor { return _gridItemDetailColor; }
+ (NSColor*)gridItemDetailTextColor { return _gridItemDetailTextColor; }
+ (NSColor*)gridItemDetailTopLineColor { return _gridItemDetailTopLineColor; }
+ (NSColor*)gridItemDetailBottomLineColor { return _gridItemDetailBottomLineColor; }
+ (NSColor*)playerBackgroundColor { return _playerBackgroundColor; }
+ (NSColor*)playerTextColor { return _playerTextColor; }
+ (NSColor*)playerLightenColor { return _playerLightenColor; }
+ (NSColor*)playerDarkenColor { return _playerDarkenColor; }
+ (NSColor*)playerButtonHighlightColor { return _playerButtonHighlightColor; }
+ (NSColor*)playerButtonBorderDarkColor { return _playerButtonBorderDarkColor; }
+ (NSColor*)playerButtonBackgroundColor { return _playerButtonBackgroundColor; }
+ (NSColor*)playerButtonBorderColor { return _playerButtonBorderColor; }
+ (NSColor*)gridItemSubscriptionBadgeDarkColor { return _gridItemSubscriptionBadgeDarkColor; }
+ (NSColor*)gridSectionHeaderTextDarkColor { return _gridSectionHeaderTextDarkColor; }
+ (NSColor*)playerTextDarkColor { return _playerTextDarkColor; }
+ (NSColor*)gridSectionHeaderDarkColor { return _gridSectionHeaderDarkColor; }
+ (NSColor*)gridItemDetailTextDarkColor { return _gridItemDetailTextDarkColor; }
+ (NSColor*)playerBackgroundDarkColor { return _playerBackgroundDarkColor; }
+ (NSColor*)playerLightenDarkColor { return _playerLightenDarkColor; }
+ (NSColor*)playerDarkenDarkColor { return _playerDarkenDarkColor; }
+ (NSColor*)playerButtonBackgroundDarkColor { return _playerButtonBackgroundDarkColor; }
+ (NSColor*)playerButtonHighlightDarkColor { return _playerButtonHighlightDarkColor; }
+ (NSColor*)userLoggedOutStatusDarkColor { return _userLoggedOutStatusDarkColor; }
+ (NSColor*)gridItemDetailBottomLineDarkColor { return _gridItemDetailBottomLineDarkColor; }
+ (NSColor*)gridItemDetailTopLineDarkColor { return _gridItemDetailTopLineDarkColor; }
+ (NSColor*)gridItemSelectionForegroundColor { return _gridItemSelectionForegroundColor; }
+ (NSColor*)gridItemSelectionBackgroundColor { return _gridItemSelectionBackgroundColor; }
+ (NSColor*)gridItemSelectionBackgroundDarkColor { return _gridItemSelectionBackgroundDarkColor; }
+ (NSColor*)gridItemDetailMarkerColor { return _gridItemDetailMarkerColor; }
+ (NSColor*)gridItemDetailMarkerDarkColor { return _gridItemDetailMarkerDarkColor; }
+ (NSColor*)gridItemSelectionForegroundDarkColor { return _gridItemSelectionForegroundDarkColor; }
+ (NSColor*)userLoggedInStatusDarkColor { return _userLoggedInStatusDarkColor; }

@end
