platform :osx, '10.12'
source 'https://github.com/CocoaPods/Specs.git'
project 'Podlive'
#use_frameworks!

target 'Podlive' do
    pod 'CCNNavigationController'
    pod 'CCNPreferencesWindowController'
    pod 'Bolts', :git => 'https://github.com/BoltsFramework/Bolts-ObjC.git'
    pod 'Parse', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git'
    pod 'libextobjc/EXTKeyPathCoding'
    pod 'libextobjc/EXTScope'
end
