language: objective-c
os: osx
osx_image: xcode10.2
branches:
  only:
    - master
    - /^v?[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/
git:
  submodules: false

before_install:
  - git submodule update --init --recursive

jobs:
  include:
    - stage: release
      env: Deployment
      install: bundle install
      script:
      - ./Scripts/jazzy.sh
      - xcrun simctl create "Apple TV 1080p" com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p com.apple.CoreSimulator.SimRuntime.tvOS-12-2
      - bundle exec rake package:release
      deploy:
        - provider: releases
          api_key:
            secure: $GITHUB_TOKEN # Set in travis-ci.org dashboard
          file_glob: true
          file: build/release/*
          skip_cleanup: true
          on:
            tags: true
            all_branches: true
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
          local_dir: docs/
          on:
            all_branches: true
    - stage: release
      env: Cocoapods
      install: bundle install
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: ./Scripts/publish.sh
        on:
          tags: true
          all_branches: true
